from fields import Fields, Field
import json
from pathlib import Path

current_dir = Path(__file__).parent

properties = {}

for key in ["meta", "main", "aux"]:
    fields = Fields.from_file(current_dir / ".." / "data" / f"{key}_fields.yaml")
    props = {}

    field: Field
    for field in fields.fields_by_key.values():
        props[field.name] = {"$ref": f"field_types.schema.json#/definitions/{field.type_name}"}

    properties[key] = {
        "type": "object",
        "properties": props,
        "unevaluatedProperties": False,
    }

result = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Auto-generated by gen_schema.py",
    "type": "object",
    "properties": properties,
    "unevaluatedProperties": False,
}
with open(current_dir / "schema" / "fields.schema.json", "w", encoding="utf-8") as f:
    json.dump(result, f, indent=4)

    # To stop precommit from complaining
    f.write("\n")
